<?php

namespace StoreBundle\Repository;

/**
 * CuotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuotaRepository extends \Doctrine\ORM\EntityRepository
{
	public function listarTodas(&$pagina,&$cantidadDePaginas) {
		$query = $this->getEntityManager()->createQuery('SELECT c from StoreBundle\Entity\Cuota c WHERE c.borrado=false ORDER BY c.fecha DESC');
		$cantidadTotal = count($query->getResult());
		$configuracion = $this->getEntityManager()->getRepository('StoreBundle:Configuracion')->findOneBy(array('clave' => 'elementosPorPagina' ));
		$elementosPorPagina = (int) $configuracion->getValor();
		if ($cantidadTotal==0) {
			$cantidadDePaginas = 1;
		}
		else {
			$cantidadDePaginas = ceil($cantidadTotal / $elementosPorPagina);
		}
		if ((int) $pagina < 1 || $pagina > $cantidadDePaginas) {
			$pagina = 1;
		}
		$primerCuota = ($pagina -1) * $elementosPorPagina;
		$query->setFirstResult($primerCuota);
		$query->setMaxResults($elementosPorPagina);
		return $query->getResult();
	}

	public function cuotasRegistradasDeAlumno($alumno) {
		$query = $this->getEntityManager()->createQuery('SELECT c FROM StoreBundle\Entity\Cuota c WHERE EXISTS 
			(SELECT p FROM StoreBundle\Entity\Pago p WHERE p.cuota = c and p.alumno = :alu) ');
		$query->setParameter('alu',$alumno);
		return $query->getResult();
	}

}
